2023-03-26 01:04:10,457 p=11186 u=kojibello n=ansible | Starting galaxy role install process
2023-03-26 01:04:10,522 p=11186 u=kojibello n=ansible | [WARNING]: - datadog.datadog was NOT installed successfully: Unknown error when attempting to call Galaxy at
'https://galaxy.ansible.com/api/': <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed:
unable to get local issuer certificate (_ssl.c:997)>

2023-03-26 01:04:10,522 p=11186 u=kojibello n=ansible | ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.
2023-03-26 01:04:51,846 p=11224 u=kojibello n=ansible | Starting galaxy role install process
2023-03-26 01:04:51,917 p=11224 u=kojibello n=ansible | [WARNING]: - datadog.datadog was NOT installed successfully: Unknown error when attempting to call Galaxy at
'https://galaxy.ansible.com/api/': <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed:
unable to get local issuer certificate (_ssl.c:997)>

2023-03-26 01:04:51,918 p=11224 u=kojibello n=ansible | ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.
2023-03-26 01:28:03,406 p=20742 u=kojibello n=ansible | 18.234.98.133 | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: Warning: Permanently added '18.234.98.133' (ECDSA) to the list of known hosts.\r\nkojibello@18.234.98.133: Permission denied (publickey,gssapi-keyex,gssapi-with-mic).",
    "unreachable": true
}
2023-03-26 01:28:03,410 p=20742 u=kojibello n=ansible | 35.174.9.86 | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: Warning: Permanently added '35.174.9.86' (ECDSA) to the list of known hosts.\r\nkojibello@35.174.9.86: Permission denied (publickey,gssapi-keyex,gssapi-with-mic).",
    "unreachable": true
}
2023-03-26 01:28:17,005 p=20767 u=kojibello n=ansible | 35.174.9.86 | SUCCESS => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/libexec/platform-python"
    },
    "changed": false,
    "ping": "pong"
}
2023-03-26 01:28:17,005 p=20767 u=kojibello n=ansible | 18.234.98.133 | SUCCESS => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/libexec/platform-python"
    },
    "changed": false,
    "ping": "pong"
}
2023-03-26 01:35:14,233 p=21251 u=kojibello n=ansible | [WARNING]: Could not match supplied host pattern, ignoring: rehat

2023-03-26 01:35:14,233 p=21251 u=kojibello n=ansible | [WARNING]: No hosts matched, nothing to do

2023-03-26 01:35:20,843 p=21268 u=kojibello n=ansible | 18.234.98.133 | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: kojibello@18.234.98.133: Permission denied (publickey,gssapi-keyex,gssapi-with-mic).",
    "unreachable": true
}
2023-03-26 01:35:20,854 p=21268 u=kojibello n=ansible | 35.174.9.86 | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: kojibello@35.174.9.86: Permission denied (publickey,gssapi-keyex,gssapi-with-mic).",
    "unreachable": true
}
2023-03-26 01:35:36,554 p=21291 u=kojibello n=ansible | 18.234.98.133 | SUCCESS => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/libexec/platform-python"
    },
    "changed": false,
    "ping": "pong"
}
2023-03-26 01:35:36,571 p=21291 u=kojibello n=ansible | 35.174.9.86 | SUCCESS => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/libexec/platform-python"
    },
    "changed": false,
    "ping": "pong"
}
2023-03-26 01:36:17,906 p=21395 u=kojibello n=ansible | PLAY [c2o Setup] ***************************************************************************************************
2023-03-26 01:36:17,918 p=21395 u=kojibello n=ansible | TASK [Gathering Facts] *********************************************************************************************
2023-03-26 01:36:19,985 p=21395 u=kojibello n=ansible | ok: [18.234.98.133]
2023-03-26 01:36:20,014 p=21395 u=kojibello n=ansible | ok: [35.174.9.86]
2023-03-26 01:36:20,029 p=21395 u=kojibello n=ansible | TASK [ping dynamic inventory] **************************************************************************************
2023-03-26 01:36:20,973 p=21395 u=kojibello n=ansible | ok: [18.234.98.133]
2023-03-26 01:36:20,985 p=21395 u=kojibello n=ansible | ok: [35.174.9.86]
2023-03-26 01:36:20,994 p=21395 u=kojibello n=ansible | TASK [include_tasks] ***********************************************************************************************
2023-03-26 01:36:21,036 p=21395 u=kojibello n=ansible | included: /Users/kojibello/Downloads/scr/c2o-web-app-configuration-on-rhel/tasks/datadog.yml for 35.174.9.86, 18.234.98.133
2023-03-26 01:36:21,043 p=21395 u=kojibello n=ansible | TASK [lookup secretsmanager secret in a specific region using specified region and aws profile using nested feature] ***
2023-03-26 01:36:21,300 p=21395 u=kojibello n=ansible | ERROR! A worker was found in a dead state
2023-03-26 01:37:38,579 p=21513 u=kojibello n=ansible | PLAY [c2o Setup] ***************************************************************************************************
2023-03-26 01:37:38,591 p=21513 u=kojibello n=ansible | TASK [Gathering Facts] *********************************************************************************************
2023-03-26 01:37:40,862 p=21513 u=kojibello n=ansible | ok: [18.234.98.133]
2023-03-26 01:37:40,883 p=21513 u=kojibello n=ansible | ok: [35.174.9.86]
2023-03-26 01:37:40,916 p=21513 u=kojibello n=ansible | TASK [ping dynamic inventory] **************************************************************************************
2023-03-26 01:37:41,945 p=21513 u=kojibello n=ansible | ok: [18.234.98.133]
2023-03-26 01:37:41,945 p=21513 u=kojibello n=ansible | ok: [35.174.9.86]
2023-03-26 01:37:41,954 p=21513 u=kojibello n=ansible | TASK [include_tasks] ***********************************************************************************************
2023-03-26 01:37:41,995 p=21513 u=kojibello n=ansible | included: /Users/kojibello/Downloads/scr/c2o-web-app-configuration-on-rhel/tasks/datadog.yml for 35.174.9.86, 18.234.98.133
2023-03-26 01:37:42,002 p=21513 u=kojibello n=ansible | TASK [lookup secretsmanager secret in a specific region using specified region and aws profile using nested feature] ***
2023-03-26 01:37:42,270 p=21513 u=kojibello n=ansible | ERROR! A worker was found in a dead state
2023-03-26 01:38:30,341 p=21619 u=kojibello n=ansible | PLAY [c2o Setup] ***************************************************************************************************
2023-03-26 01:38:30,353 p=21619 u=kojibello n=ansible | TASK [Gathering Facts] *********************************************************************************************
2023-03-26 01:38:32,055 p=21619 u=kojibello n=ansible | ok: [18.234.98.133]
2023-03-26 01:38:32,113 p=21619 u=kojibello n=ansible | ok: [35.174.9.86]
2023-03-26 01:38:32,129 p=21619 u=kojibello n=ansible | TASK [ping dynamic inventory] **************************************************************************************
2023-03-26 01:38:33,035 p=21619 u=kojibello n=ansible | ok: [35.174.9.86]
2023-03-26 01:38:33,076 p=21619 u=kojibello n=ansible | ok: [18.234.98.133]
2023-03-26 01:38:33,087 p=21619 u=kojibello n=ansible | TASK [include_tasks] ***********************************************************************************************
2023-03-26 01:38:33,129 p=21619 u=kojibello n=ansible | included: /Users/kojibello/Downloads/scr/c2o-web-app-configuration-on-rhel/tasks/datadog.yml for 35.174.9.86, 18.234.98.133
2023-03-26 01:38:33,139 p=21619 u=kojibello n=ansible | TASK [lookup secretsmanager secret in a specific region using specified region and aws profile using nested feature] ***
2023-03-26 01:38:33,365 p=21619 u=kojibello n=ansible | ERROR! A worker was found in a dead state
2023-03-26 01:38:45,703 p=21684 u=kojibello n=ansible | PLAY [c2o Setup] ***************************************************************************************************
2023-03-26 01:38:45,713 p=21684 u=kojibello n=ansible | TASK [Gathering Facts] *********************************************************************************************
2023-03-26 01:38:48,860 p=21684 u=kojibello n=ansible | ok: [18.234.98.133]
2023-03-26 01:38:48,861 p=21684 u=kojibello n=ansible | ok: [35.174.9.86]
2023-03-26 01:38:48,874 p=21684 u=kojibello n=ansible | TASK [ping dynamic inventory] **************************************************************************************
2023-03-26 01:38:50,043 p=21684 u=kojibello n=ansible | ok: [18.234.98.133]
2023-03-26 01:38:50,051 p=21684 u=kojibello n=ansible | ok: [35.174.9.86]
2023-03-26 01:38:50,061 p=21684 u=kojibello n=ansible | TASK [include_tasks] ***********************************************************************************************
2023-03-26 01:38:50,102 p=21684 u=kojibello n=ansible | included: /Users/kojibello/Downloads/scr/c2o-web-app-configuration-on-rhel/tasks/datadog.yml for 35.174.9.86, 18.234.98.133
2023-03-26 01:38:50,109 p=21684 u=kojibello n=ansible | TASK [lookup secretsmanager secret in a specific region using specified region and aws profile using nested feature] ***
2023-03-26 01:38:50,262 p=21684 u=kojibello n=ansible | ERROR! A worker was found in a dead state
2023-03-26 01:40:02,578 p=21828 u=kojibello n=ansible | PLAY [c2o Setup] ***************************************************************************************************
2023-03-26 01:40:02,591 p=21828 u=kojibello n=ansible | TASK [Gathering Facts] *********************************************************************************************
2023-03-26 01:40:04,972 p=21828 u=kojibello n=ansible | ok: [35.174.9.86]
2023-03-26 01:40:04,973 p=21828 u=kojibello n=ansible | ok: [18.234.98.133]
2023-03-26 01:40:04,986 p=21828 u=kojibello n=ansible | TASK [ping dynamic inventory] **************************************************************************************
2023-03-26 01:40:05,922 p=21828 u=kojibello n=ansible | ok: [18.234.98.133]
2023-03-26 01:40:05,947 p=21828 u=kojibello n=ansible | ok: [35.174.9.86]
2023-03-26 01:40:05,956 p=21828 u=kojibello n=ansible | TASK [include_tasks] ***********************************************************************************************
2023-03-26 01:40:05,998 p=21828 u=kojibello n=ansible | included: /Users/kojibello/Downloads/scr/c2o-web-app-configuration-on-rhel/tasks/datadog.yml for 35.174.9.86, 18.234.98.133
2023-03-26 01:40:06,006 p=21828 u=kojibello n=ansible | TASK [lookup secretsmanager secret in a specific region using specified region and aws profile using nested feature] ***
2023-03-26 01:40:06,249 p=21828 u=kojibello n=ansible | ERROR! A worker was found in a dead state
2023-03-26 01:43:55,417 p=22213 u=kojibello n=ansible | PLAY [c2o Setup] ***************************************************************************************************
2023-03-26 01:43:55,430 p=22213 u=kojibello n=ansible | TASK [Gathering Facts] *********************************************************************************************
2023-03-26 01:43:59,045 p=22213 u=kojibello n=ansible | ok: [18.234.98.133]
2023-03-26 01:43:59,074 p=22213 u=kojibello n=ansible | ok: [35.174.9.86]
2023-03-26 01:43:59,088 p=22213 u=kojibello n=ansible | TASK [ping dynamic inventory] **************************************************************************************
2023-03-26 01:44:00,615 p=22213 u=kojibello n=ansible | ok: [35.174.9.86]
2023-03-26 01:44:00,721 p=22213 u=kojibello n=ansible | ok: [18.234.98.133]
2023-03-26 01:44:00,730 p=22213 u=kojibello n=ansible | TASK [include_tasks] ***********************************************************************************************
2023-03-26 01:44:00,770 p=22213 u=kojibello n=ansible | fatal: [35.174.9.86]: FAILED! => {"reason": "unexpected parameter type in action: <class 'ansible.parsing.yaml.objects.AnsibleSequence'>\n\nThe error appears to be in '/Users/kojibello/Downloads/scr/c2o-web-app-configuration-on-rhel/tasks/datadog.yml': line 2, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Install Datadog Agent on servers in aws\n  ^ here\n"}
2023-03-26 01:44:00,770 p=22213 u=kojibello n=ansible | fatal: [18.234.98.133]: FAILED! => {"reason": "unexpected parameter type in action: <class 'ansible.parsing.yaml.objects.AnsibleSequence'>\n\nThe error appears to be in '/Users/kojibello/Downloads/scr/c2o-web-app-configuration-on-rhel/tasks/datadog.yml': line 2, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Install Datadog Agent on servers in aws\n  ^ here\n"}
2023-03-26 01:44:00,771 p=22213 u=kojibello n=ansible | PLAY RECAP *********************************************************************************************************
2023-03-26 01:44:00,771 p=22213 u=kojibello n=ansible | 18.234.98.133              : ok=2    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
2023-03-26 01:44:00,771 p=22213 u=kojibello n=ansible | 35.174.9.86                : ok=2    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
2023-03-26 01:45:32,831 p=22394 u=kojibello n=ansible | PLAY [c2o Setup] ***************************************************************************************************
2023-03-26 01:45:32,844 p=22394 u=kojibello n=ansible | TASK [Gathering Facts] *********************************************************************************************
2023-03-26 01:45:35,213 p=22394 u=kojibello n=ansible | ok: [35.174.9.86]
2023-03-26 01:45:35,214 p=22394 u=kojibello n=ansible | ok: [18.234.98.133]
2023-03-26 01:45:35,227 p=22394 u=kojibello n=ansible | TASK [ping dynamic inventory] **************************************************************************************
2023-03-26 01:45:36,151 p=22394 u=kojibello n=ansible | ok: [18.234.98.133]
2023-03-26 01:45:36,151 p=22394 u=kojibello n=ansible | ok: [35.174.9.86]
2023-03-26 01:45:36,159 p=22394 u=kojibello n=ansible | TASK [include_tasks] ***********************************************************************************************
2023-03-26 01:45:36,199 p=22394 u=kojibello n=ansible | fatal: [35.174.9.86]: FAILED! => {"reason": "unexpected parameter type in action: <class 'ansible.parsing.yaml.objects.AnsibleSequence'>\n\nThe error appears to be in '/Users/kojibello/Downloads/scr/c2o-web-app-configuration-on-rhel/tasks/datadog.yml': line 2, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n---\n- name: Install Datadog Agent on servers in aws\n  ^ here\n"}
2023-03-26 01:45:36,199 p=22394 u=kojibello n=ansible | fatal: [18.234.98.133]: FAILED! => {"reason": "unexpected parameter type in action: <class 'ansible.parsing.yaml.objects.AnsibleSequence'>\n\nThe error appears to be in '/Users/kojibello/Downloads/scr/c2o-web-app-configuration-on-rhel/tasks/datadog.yml': line 2, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n---\n- name: Install Datadog Agent on servers in aws\n  ^ here\n"}
2023-03-26 01:45:36,200 p=22394 u=kojibello n=ansible | PLAY RECAP *********************************************************************************************************
2023-03-26 01:45:36,200 p=22394 u=kojibello n=ansible | 18.234.98.133              : ok=2    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
2023-03-26 01:45:36,200 p=22394 u=kojibello n=ansible | 35.174.9.86                : ok=2    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
2023-03-26 01:45:45,568 p=22454 u=kojibello n=ansible | PLAY [c2o Setup] ***************************************************************************************************
2023-03-26 01:45:45,578 p=22454 u=kojibello n=ansible | TASK [Gathering Facts] *********************************************************************************************
2023-03-26 01:45:47,384 p=22454 u=kojibello n=ansible | ok: [18.234.98.133]
2023-03-26 01:45:47,385 p=22454 u=kojibello n=ansible | ok: [35.174.9.86]
2023-03-26 01:45:47,400 p=22454 u=kojibello n=ansible | TASK [ping dynamic inventory] **************************************************************************************
2023-03-26 01:45:48,384 p=22454 u=kojibello n=ansible | ok: [18.234.98.133]
2023-03-26 01:45:48,394 p=22454 u=kojibello n=ansible | ok: [35.174.9.86]
2023-03-26 01:45:48,402 p=22454 u=kojibello n=ansible | TASK [include_tasks] ***********************************************************************************************
2023-03-26 01:45:48,444 p=22454 u=kojibello n=ansible | fatal: [35.174.9.86]: FAILED! => {"reason": "unexpected parameter type in action: <class 'ansible.parsing.yaml.objects.AnsibleSequence'>\n\nThe error appears to be in '/Users/kojibello/Downloads/scr/c2o-web-app-configuration-on-rhel/tasks/datadog.yml': line 2, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n---\n- name: Install Datadog Agent on servers in aws\n  ^ here\n"}
2023-03-26 01:45:48,445 p=22454 u=kojibello n=ansible | fatal: [18.234.98.133]: FAILED! => {"reason": "unexpected parameter type in action: <class 'ansible.parsing.yaml.objects.AnsibleSequence'>\n\nThe error appears to be in '/Users/kojibello/Downloads/scr/c2o-web-app-configuration-on-rhel/tasks/datadog.yml': line 2, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n---\n- name: Install Datadog Agent on servers in aws\n  ^ here\n"}
2023-03-26 01:45:48,446 p=22454 u=kojibello n=ansible | PLAY RECAP *********************************************************************************************************
2023-03-26 01:45:48,446 p=22454 u=kojibello n=ansible | 18.234.98.133              : ok=2    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
2023-03-26 01:45:48,446 p=22454 u=kojibello n=ansible | 35.174.9.86                : ok=2    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
2023-03-26 01:47:56,049 p=22631 u=kojibello n=ansible | PLAY [c2o Setup] ***************************************************************************************************
2023-03-26 01:47:56,062 p=22631 u=kojibello n=ansible | TASK [Gathering Facts] *********************************************************************************************
2023-03-26 01:47:58,360 p=22631 u=kojibello n=ansible | ok: [18.234.98.133]
2023-03-26 01:47:58,361 p=22631 u=kojibello n=ansible | ok: [35.174.9.86]
2023-03-26 01:47:58,374 p=22631 u=kojibello n=ansible | TASK [ping dynamic inventory] **************************************************************************************
2023-03-26 01:48:00,447 p=22631 u=kojibello n=ansible | ok: [18.234.98.133]
2023-03-26 01:48:00,447 p=22631 u=kojibello n=ansible | ok: [35.174.9.86]
2023-03-26 01:48:00,455 p=22631 u=kojibello n=ansible | TASK [include_tasks] ***********************************************************************************************
2023-03-26 01:48:00,495 p=22631 u=kojibello n=ansible | fatal: [35.174.9.86]: FAILED! => {"reason": "Could not find or access '/Users/kojibello/Downloads/scr/c2o-web-app-configuration-on-rhel/tasks/datadog.yml' on the Ansible Controller."}
2023-03-26 01:48:00,495 p=22631 u=kojibello n=ansible | fatal: [18.234.98.133]: FAILED! => {"reason": "Could not find or access '/Users/kojibello/Downloads/scr/c2o-web-app-configuration-on-rhel/tasks/datadog.yml' on the Ansible Controller."}
2023-03-26 01:48:00,496 p=22631 u=kojibello n=ansible | PLAY RECAP *********************************************************************************************************
2023-03-26 01:48:00,496 p=22631 u=kojibello n=ansible | 18.234.98.133              : ok=2    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
2023-03-26 01:48:00,497 p=22631 u=kojibello n=ansible | 35.174.9.86                : ok=2    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
2023-03-26 01:48:21,184 p=22710 u=kojibello n=ansible | ERROR! the role 'datadog.datadog' was not found in /Users/kojibello/Downloads/scr/c2o-web-app-configuration-on-rhel/roles:/Users/kojibello/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:/Users/kojibello/Downloads/scr/c2o-web-app-configuration-on-rhel

The error appears to be in '/Users/kojibello/Downloads/scr/c2o-web-app-configuration-on-rhel/datadog.yml': line 8, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  roles:
    - { role: datadog.datadog, become: yes}
      ^ here

2023-03-26 01:49:56,981 p=22836 u=kojibello n=ansible | ERROR! the role 'datadog.datadog' was not found in /Users/kojibello/Downloads/scr/c2o-web-app-configuration-on-rhel/roles:/Users/kojibello/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:/Users/kojibello/Downloads/scr/c2o-web-app-configuration-on-rhel

The error appears to be in '/Users/kojibello/Downloads/scr/c2o-web-app-configuration-on-rhel/datadog.yml': line 6, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  roles:
    - { role: datadog.datadog, become: yes}
      ^ here

2023-03-26 01:50:07,808 p=22852 u=kojibello n=ansible | Starting galaxy role install process
2023-03-26 01:50:07,853 p=22852 u=kojibello n=ansible | [WARNING]: - datadog.datadog was NOT installed successfully: Unknown error when attempting to call Galaxy at
'https://galaxy.ansible.com/api/': <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed:
unable to get local issuer certificate (_ssl.c:997)>

2023-03-26 01:50:07,853 p=22852 u=kojibello n=ansible | ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.
2023-03-26 01:50:15,058 p=22859 u=kojibello n=ansible | Starting galaxy role install process
2023-03-26 01:50:15,107 p=22859 u=kojibello n=ansible | [WARNING]: - datadog.datadog was NOT installed successfully: Unknown error when attempting to call Galaxy at
'https://galaxy.ansible.com/api/': <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed:
unable to get local issuer certificate (_ssl.c:997)>

2023-03-26 01:51:06,072 p=22915 u=kojibello n=ansible | Starting galaxy role install process
2023-03-26 01:51:06,132 p=22915 u=kojibello n=ansible | [WARNING]: - datadog.datadog was NOT installed successfully: Unknown error when attempting to call Galaxy at
'https://galaxy.ansible.com/api/': <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed:
unable to get local issuer certificate (_ssl.c:997)>

2023-03-26 01:51:06,132 p=22915 u=kojibello n=ansible | ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.
